export const RENEWAL_FEATURES = [
  {
    id: 'xenserver',
    label: 'XenServer adoption',
    availableFor: ['CPC', 'HMC'],
    category: 'Hypervisor',
    description: 'Riduzione o eliminazione dei costi hypervisor di terze parti.',
    calculationKey: 'xenserver',
  },
  {
    id: 'cvadPremiumFeatures',
    label: 'CVAD premium features',
    availableFor: ['CPC'],
    category: 'Virtual Apps and Desktops',
    description: 'Valore da consolidamento o adozione di feature premium non ancora implementate.',
    calculationKey: 'manualCvadPremium',
  },
  {
    id: 'platformRiskReduction',
    label: 'Platform risk reduction',
    availableFor: ['CPC'],
    category: 'Risk',
    description: 'Riduzione del rischio operativo e dei costi di piattaforma.',
    calculationKey: 'manualPlatformRisk',
  },
  {
    id: 'infrastructureOptimization',
    label: 'Infrastructure optimization',
    availableFor: ['CPC'],
    category: 'Infrastructure',
    description: 'Ottimizzazione infrastrutturale abilitata dal rinnovo.',
    calculationKey: 'manualInfrastructureOptimization',
  },
  {
    id: 'netscaler',
    label: 'NetScaler',
    availableFor: ['HMC'],
    category: 'Access / ADC',
    description: 'Riduzione costi VPN, ADC e appliance sovrapposte.',
    calculationKey: 'netscaler',
  },
  {
    id: 'uniconElux',
    label: 'Unicon/eLux',
    availableFor: ['HMC'],
    category: 'Endpoint',
    description: 'Estensione vita endpoint e conversione dispositivi compatibili.',
    calculationKey: 'uniconElux',
  },
  {
    id: 'endpointLifecycleExtension',
    label: 'Endpoint lifecycle extension',
    availableFor: ['HMC'],
    category: 'Endpoint',
    description: 'Riduzione refresh PC tramite estensione lifecycle.',
    calculationKey: 'endpointLifecycle',
  },
  {
    id: 'mfaZtnaOverlapReduction',
    label: 'MFA/ZTNA overlap reduction',
    availableFor: ['HMC'],
    category: 'Security',
    description: 'Riduzione costi di strumenti MFA/ZTNA sovrapposti.',
    calculationKey: 'mfaZtna',
  },
  {
    id: 'itEffortReduction',
    label: 'IT effort reduction',
    availableFor: ['HMC'],
    category: 'Operations',
    description: 'Riduzione effort IT operativo.',
    calculationKey: 'itEffort',
  },
  {
    id: 'edrPostureSocOptimization',
    label: 'EDR/Posture/SOC optimization',
    availableFor: ['HMC'],
    category: 'Security',
    description: 'Riduzione costi residui EDR, posture, SOC e remediation.',
    calculationKey: 'securityOps',
  },
];
