export const RENEWAL_FEATURES = [
  {
    id: 'xenserver',
    label: 'XenServer adoption',
    availableFor: ['CPC', 'HMC'],
    category: 'Hypervisor',
    description: 'Riduzione o eliminazione dei costi hypervisor di terze parti.',
    calculationKey: 'xenserver',
    adoption: {
      xenserver: {
        currentAdopted: true,
        currentAdoptionPct: 40,
        targetAdoptable: true,
        potentialAdoptionPct: 90,
        manualAnnualSaving: 0,
      },
    },
  },
  {
    id: 'cvadPremiumFeatures',
    label: 'CVAD premium features',
    availableFor: ['CPC'],
    category: 'Virtual Apps and Desktops',
    description: 'Valore da consolidamento o adozione di feature premium non ancora implementate.',
    calculationKey: 'manualCvadPremium',
    adoption: {
      cvadPremiumFeatures: {
        currentAdopted: false,
        currentAdoptionPct: 10,
        targetAdoptable: true,
        potentialAdoptionPct: 65,
        manualAnnualSaving: 0,
      },
    },
  },
  {
    id: 'platformRiskReduction',
    label: 'Platform risk reduction',
    availableFor: ['CPC'],
    category: 'Risk',
    description: 'Riduzione del rischio operativo e dei costi di piattaforma.',
    calculationKey: 'manualPlatformRisk',
    adoption: {
      platformRiskReduction: {
        currentAdopted: false,
        currentAdoptionPct: 15,
        targetAdoptable: true,
        potentialAdoptionPct: 70,
        manualAnnualSaving: 0,
      },
    },
  },
  {
    id: 'infrastructureOptimization',
    label: 'Infrastructure optimization',
    availableFor: ['CPC'],
    category: 'Infrastructure',
    description: 'Ottimizzazione infrastrutturale abilitata dal rinnovo.',
    calculationKey: 'manualInfrastructureOptimization',
    adoption: {
      infrastructureOptimization: {
        currentAdopted: false,
        currentAdoptionPct: 20,
        targetAdoptable: true,
        potentialAdoptionPct: 75,
        manualAnnualSaving: 0,
      },
    },
  },
  {
    id: 'netscaler',
    label: 'NetScaler',
    availableFor: ['HMC'],
    category: 'Access / ADC',
    description: 'Riduzione costi VPN, ADC e appliance sovrapposte.',
    calculationKey: 'netscaler',
    adoption: {
      netscaler: {
        currentAdopted: false,
        currentAdoptionPct: 25,
        targetAdoptable: true,
        potentialAdoptionPct: 85,
        manualAnnualSaving: 0,
      },
    },
  },
  {
    id: 'uniconElux',
    label: 'Unicon/eLux',
    availableFor: ['HMC'],
    category: 'Endpoint',
    description: 'Estensione vita endpoint e conversione dispositivi compatibili.',
    calculationKey: 'uniconElux',
    adoption: {
      uniconElux: {
        currentAdopted: false,
        currentAdoptionPct: 10,
        targetAdoptable: true,
        potentialAdoptionPct: 70,
        manualAnnualSaving: 0,
      },
    },
  },
  {
    id: 'endpointLifecycleExtension',
    label: 'Endpoint lifecycle extension',
    availableFor: ['HMC'],
    category: 'Endpoint',
    description: 'Riduzione refresh PC tramite estensione lifecycle.',
    calculationKey: 'endpointLifecycle',
    adoption: {
      endpointLifecycleExtension: {
        currentAdopted: true,
        currentAdoptionPct: 35,
        targetAdoptable: true,
        potentialAdoptionPct: 80,
        manualAnnualSaving: 0,
      },
    },
  },
  {
    id: 'mfaZtnaOverlapReduction',
    label: 'MFA/ZTNA overlap reduction',
    availableFor: ['HMC'],
    category: 'Security',
    description: 'Riduzione costi di strumenti MFA/ZTNA sovrapposti.',
    calculationKey: 'mfaZtna',
    adoption: {
      mfaZtnaOverlapReduction: {
        currentAdopted: false,
        currentAdoptionPct: 20,
        targetAdoptable: true,
        potentialAdoptionPct: 75,
        manualAnnualSaving: 0,
      },
    },
  },
  {
    id: 'itEffortReduction',
    label: 'IT effort reduction',
    availableFor: ['HMC'],
    category: 'Operations',
    description: 'Riduzione effort IT operativo.',
    calculationKey: 'itEffort',
    adoption: {
      itEffortReduction: {
        currentAdopted: true,
        currentAdoptionPct: 30,
        targetAdoptable: true,
        potentialAdoptionPct: 70,
        manualAnnualSaving: 0,
      },
    },
  },
  {
    id: 'edrPostureSocOptimization',
    label: 'EDR/Posture/SOC optimization',
    availableFor: ['HMC'],
    category: 'Security',
    description: 'Riduzione costi residui EDR, posture, SOC e remediation.',
    calculationKey: 'securityOps',
    adoption: {
      edrPostureSocOptimization: {
        currentAdopted: false,
        currentAdoptionPct: 15,
        targetAdoptable: true,
        potentialAdoptionPct: 65,
        manualAnnualSaving: 0,
      },
    },
  },
];
