import React from 'react';
import { LABELS } from './i18n/labels';
import { assessmentLevers, calculateCustomerScenario, calculateOpportunity } from './models/customerAssessmentModel';

export const wording = (lang) => (it, en, es = en, de = en) => ({ it, en, es, de }[lang] ?? en);
export const money = (value, lang = 'it') => new Intl.NumberFormat({ it: 'it-IT', en: 'en-US', es: 'es-ES', de: 'de-DE' }[lang] ?? 'en-US', { style: 'currency', currency: 'EUR', maximumFractionDigits: 0 }).format(value);
export const buttonStyle = 'rounded-xl bg-blue-700 px-4 py-2.5 text-sm font-semibold text-white hover:bg-blue-600';
export function Card({ title, subtitle, children }) {
  return <section className="rounded-3xl border border-slate-200 bg-white shadow-sm"><div className="border-b border-slate-100 px-6 py-5"><h2 className="text-lg font-semibold">{title}</h2>{subtitle && <p className="mt-1 text-sm leading-6 text-slate-500">{subtitle}</p>}</div><div className="p-6">{children}</div></section>;
}
export function Input({ label, value, onChange, suffix, max, step = 'any', testId, placeholder = '—' }) {
  return <label className="block space-y-2"><span className="block text-sm font-medium text-slate-700">{label}{suffix && <span className="ml-1 text-xs text-slate-500">({suffix})</span>}</span><input data-testid={testId} type="number" min="0" max={max} step={step} value={value ?? ''} placeholder={placeholder} onChange={(e) => onChange(e.target.value === '' ? '' : Math.max(0, Number(e.target.value)))} className="w-full rounded-xl border border-slate-300 bg-white px-3 py-2.5 text-sm outline-none focus:border-blue-500 focus:ring-2 focus:ring-blue-100" /></label>;
}
export function Metric({ label, value, hint }) {
  return <div className="rounded-2xl bg-slate-50 p-4"><p className="text-xs font-semibold uppercase tracking-wide text-slate-500">{label}</p><p className="mt-2 text-xl font-semibold text-slate-950">{value}</p>{hint && <p className="mt-2 text-xs leading-5 text-slate-500">{hint}</p>}</div>;
}
export function unitLabel(unit, t) {
  return { units: t('unità', 'units', 'unidades', 'Einheiten'), hosts: 'host', users: t('utenti', 'users', 'usuarios', 'Benutzer'), days: t('giorni/anno', 'days/year', 'días/año', 'Tage/Jahr'), eurYear: t('€/anno', '€/year', '€/año', '€/Jahr') }[unit];
}

export function AssessmentSummary({ state, lang, onEdit }) {
  const t = wording(lang);
  return <Card title={t('Assessment cliente condiviso', 'Shared customer assessment', 'Assessment compartido', 'Gemeinsames Kunden-Assessment')} subtitle={t('Gli stessi dati alimentano entrambe le analisi. I totali includono la quota già implementata.', 'The same data feeds both analyses. Totals include the already implemented portion.')}>
    <div className="flex flex-wrap items-center justify-between gap-4"><div className="flex flex-wrap gap-6 text-sm"><span><strong>{state.tech.numberUsers}</strong> {t('utenti', 'users')}</span><span><strong>{state.tech.numberPc}</strong> PC</span><span><strong>{state.tech.numberHosts}</strong> host</span><span><strong>{state.tech.numberVpnAdcAppliances}</strong> VPN / ADC</span></div><button className={buttonStyle} onClick={onEdit}>{t('Apri assessment', 'Open assessment', 'Abrir assessment', 'Assessment öffnen')}</button></div>
  </Card>;
}

export function CustomerAssessment({ state, setState, lang, onNavigate, onCompatibility }) {
  const t = wording(lang);
  const c = LABELS[lang];
  const update = (section, key, value) => setState((s) => ({ ...s, [section]: { ...s[section], [key]: value } }));
  const updateAdoption = (id, key, value) => setState((s) => ({ ...s, adoption: { ...s.adoption, [id]: { ...s.adoption?.[id], [key]: value } } }));
  const fields = (section, entries) => <div className="grid gap-5 md:grid-cols-2 xl:grid-cols-3">{entries.map(([key, label, suffix, max]) => <Input key={key} label={label} suffix={suffix} max={max} value={state[section][key]} onChange={(v) => update(section, key, v)} testId={`assessment-${key}`} />)}</div>;
  return <div className="space-y-6" data-testid="customer-assessment">
    <Card title={t('1. Perimetro complessivo', '1. Overall scope')} subtitle={t('Inserisci i totali di riferimento prima degli interventi: 8 host totali comprendono anche i 2 già migrati. I valori iniziali sono esempi modificabili.', 'Enter reference totals before adoption: 8 total hosts include the 2 already migrated. Initial values are editable examples.')}>
      {fields('tech', [['numberUsers', c.users], ['pctRemoteHybridUsers', c.remote, '%', 100], ['pctByodUsers', c.byod, '%', 100], ['numberPc', c.pcCount], ['numberThinClient', c.thinClients], ['avgPcAgeYears', t('Ciclo di rinnovo PC di riferimento', 'Baseline PC replacement cycle'), c.yearsSuffix], ['numberHosts', c.hosts], ['coresPerHost', c.cores], ['numberVpnAdcAppliances', c.vpnAdc]])}
    </Card>
    <Card title={t('2. Costi e effort di riferimento', '2. Reference costs and effort')} subtitle={t('Costi prima dei saving già conseguiti. Non reinserire qui la spesa residua dopo l’adozione: verrebbe sottratta due volte.', 'Costs before achieved savings. Do not enter remaining spend after adoption here: it would be subtracted twice.')}>
      {fields('cost', [['costOnePc', c.newPcCost, '€'], ['costHypervisorPerCoreYear', c.hypervisorCostCoreYear, '€'], ['costVpnAdcAppliance', c.vpnApplianceCost, '€'], ['applianceMaintenanceAnnualPct', c.applianceMaintenance, '%', 100], ['costMfaUserMonth', c.mfaCost, '€'], ['costZtnaUserMonth', c.ztnaCost, '€'], ['costEdrEndpointMonth', c.edrCost, '€'], ['costDevicePostureEndpointMonth', c.postureCost, '€'], ['costSocMsspAnnual', c.socCost, '€'], ['costRemediationPerEndpointYear', c.remediationCost, '€'], ['costSysadminDay', c.sysadminDayCost, '€']])}
      <div className="mt-6 border-t pt-6">{fields('tech', [['itDaysEndpointMgmt', c.itDaysEndpoint, c.daysYear], ['itDaysImageVdiMgmt', c.itDaysImage, c.daysYear], ['itDaysSupport', c.itDaysSupport, c.daysYear], ['itDaysAccessMgmt', c.itDaysAccess, c.daysYear], ['itDaysSecurityOps', c.itDaysSecurity, c.daysYear]])}</div>
      <details className="mt-6 rounded-xl bg-slate-50 p-4"><summary className="cursor-pointer text-sm font-semibold">{t('Altre opportunità CPC · basi economiche documentate', 'Other CPC opportunities · documented cost baselines')}</summary><p className="my-3 text-sm text-slate-500">{t('Inserisci soltanto costi distinti dalle altre voci. Una riduzione del rischio non quantificata resta esclusa dal saving.', 'Only enter costs separate from the other items. Unquantified risk reduction is excluded from savings.')}</p><div className="grid gap-4 md:grid-cols-3">{['cvadPremium', 'platformRisk', 'infrastructure'].map((id) => <Input key={id} label={{ cvadPremium: 'CVAD Premium', platformRisk: 'Platform risk', infrastructure: 'Infrastructure optimization' }[id]} value={state.manualBaselines?.[id]} onChange={(v) => update('manualBaselines', id, v)} suffix="€/anno" />)}</div></details>
    </Card>
    <Card title={t('3. Adozione attuale e benefici conseguiti', '3. Current adoption and achieved benefits')} subtitle={t('Dichiara le quantità già implementate. Per effort IT indica i giorni già risparmiati; per SOC e remediation gli euro/anno già eliminati. Il beneficio annuo è quello verificato, non una percentuale preimpostata. Se non è noto, lascia vuoto.', 'Declare implemented quantities. For IT effort enter days already saved; for SOC and remediation enter euros/year already removed. Annual benefit is verified, not a preset percentage. Leave unknown data blank.')}>
      <div className="space-y-3">{assessmentLevers(state).filter((l) => l.total > 0 || state.adoption?.[l.id]?.current).map((lever) => {
        const a = state.adoption?.[lever.id] ?? {};
        const row = calculateOpportunity(lever, a);
        return <div key={lever.id} className="rounded-2xl border border-slate-200 p-4"><div className="grid items-end gap-4 md:grid-cols-3"><div><h3 className="font-semibold">{lever.label}</h3><p className="mt-1 text-sm text-slate-500">{t('Totale', 'Total')}: {lever.total} {unitLabel(lever.unit, t)}</p><p className="mt-1 text-xs text-slate-500">{t('Costo annuo di riferimento', 'Reference annual cost')}: {money(lever.annualBaseline, lang)}</p></div><Input testId={`current-${lever.id}`} label={t('Già implementato / risparmiato', 'Already implemented / saved')} value={a.current} max={lever.total} suffix={unitLabel(lever.unit, t)} onChange={(v) => updateAdoption(lever.id, 'current', v)} />{lever.unit === 'eurYear' || lever.unit === 'days' ? <Metric label={t('Beneficio annuo calcolato', 'Calculated annual benefit')} value={row.currentValid ? money(row.alreadySaving, lang) : '—'} /> : <Input testId={`realized-${lever.id}`} label={t('Beneficio annuo già conseguito', 'Annual benefit already achieved')} value={a.current === 0 ? 0 : a.annualSaving} max={lever.annualBaseline} suffix="€" onChange={(v) => updateAdoption(lever.id, 'annualSaving', v)} />}</div>
          <p className={`mt-3 text-xs ${row.baselineValid ? 'text-emerald-700' : 'text-amber-700'}`}>{row.baselineValid ? `${t('Adozione', 'Adoption')}: ${row.currentPct.toFixed(0)}% · ${t('Spesa annua residua', 'Remaining annual spend')}: ${money(row.remainingAnnualCost, lang)}` : t('Da completare: quantità entro il totale e beneficio annuo verificato (0 se i costi non sono ancora cessati).', 'Complete quantity within total and verified annual benefit (0 if costs have not stopped yet).')}</p>
        </div>;
      })}</div>
      <div className="mt-5 flex flex-wrap gap-3"><button className={buttonStyle} onClick={() => onCompatibility('compatibility')}>XenServer compatibility</button><button className={buttonStyle} onClick={() => onCompatibility('endpointCompatibility')}>eLux compatibility</button></div>
    </Card>
    <Card title={t('Scegli l’analisi economica', 'Choose the economic analysis')} subtitle={t('L’assessment rimane condiviso. Prezzi, costi di progetto e obiettivi sono specifici di ciascuno scenario.', 'The assessment stays shared. Pricing, project costs and targets are specific to each scenario.')}><div className="grid gap-4 md:grid-cols-2"><button className={buttonStyle} onClick={() => onNavigate('newBusiness')}>New Business ROI →</button><button className={buttonStyle} onClick={() => onNavigate('renewal')}>Renewal Value →</button></div></Card>
  </div>;
}

export function OpportunityPlanner({ state, plans, setPlans, offer, years, lang, onEdit, newBusiness = false }) {
  const t = wording(lang);
  const model = calculateCustomerScenario(state, plans, offer, years);
  const update = (id, key, value) => setPlans((current) => ({ ...current, [id]: { ...current[id], [key]: value } }));
  return <Card title={newBusiness ? t('Obiettivi New Business', 'New Business targets') : `${t('Adozione e saving residuo', 'Adoption and remaining saving')} · ${offer}`} subtitle={t('Obiettivo = quantità totale a intervento completato, inclusa la parte già adottata. Compila solo le opportunità pertinenti; le altre possono essere escluse.', 'Target = total quantity after completion, including existing adoption. Complete relevant opportunities; others can be excluded.')}>
    <div className="mb-5 rounded-xl bg-blue-50 p-4 text-sm leading-6 text-blue-950">{t('Nessun saving viene attribuito ai dati mancanti. Il totale è parziale finché ci sono voci da completare. Le quantità attuali si modificano nell’assessment.', 'Missing data generates no saving. Totals are partial while items are incomplete. Edit current quantities in the assessment.')} <button className="font-semibold underline" onClick={onEdit}>{t('Apri assessment', 'Open assessment')}</button></div>
    <div className="space-y-4">{model.rows.map((row) => {
      const p = plans[row.id] ?? {};
      const status = row.excluded ? t('Escluso', 'Excluded') : !row.baselineValid ? t('Assessment da completare', 'Assessment incomplete') : row.complete ? t('Dati completi', 'Data complete') : t('Obiettivo da completare', 'Target incomplete');
      return <details key={row.id} className="rounded-2xl border border-slate-200" open={row.id === 'xenserver' ? true : undefined}><summary className="cursor-pointer p-4"><span className="font-semibold">{row.label}</span><span className="ml-3 text-xs text-slate-500">{status}</span><span className="mt-2 block text-sm text-slate-600">{t('Totale', 'Total')} {row.total} · {t('Già implementato', 'Already implemented')} {row.currentValid ? row.current : '—'} · {t('Da completare', 'Remaining to target')} {row.targetValid ? row.gap : '—'} {unitLabel(row.unit, t)}</span></summary>
        <div className="border-t border-slate-100 p-4">
          <div className="mb-4 grid gap-3 sm:grid-cols-3"><Metric label={t('Adozione attuale', 'Current adoption')} value={row.currentValid ? `${row.currentPct.toFixed(0)}%` : '—'} hint={!row.currentValid ? t('Da verificare', 'To verify') : row.current === 0 ? t('Non avviata', 'Not started') : row.current < row.total ? t('Adozione parziale', 'Partial adoption') : t('Adozione completa', 'Full adoption')} /><Metric label={t('Beneficio annuo già conseguito', 'Achieved annual benefit')} value={row.baselineValid ? money(row.alreadySaving, lang) : '—'} /><Metric label={t('Saving aggiuntivo annuo', 'Additional annual saving')} value={row.complete ? money(row.annualSaving, lang) : '—'} /></div>
          <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3"><label className="block space-y-2 text-sm font-medium text-slate-700">{t('Fattibilità intervento', 'Implementation feasibility')}<select data-testid={`feasibility-${row.id}`} value={p.feasibility ?? ''} onChange={(e) => update(row.id, 'feasibility', e.target.value)} className="block w-full rounded-xl border border-slate-300 p-2.5"><option value="">{t('Da verificare', 'To verify')}</option><option value="yes">{t('Confermata', 'Confirmed')}</option><option value="no">{t('Escluso / non previsto', 'Excluded / not planned')}</option></select></label>
            <Input testId={`target-${row.id}`} label={t('Obiettivo totale raggiungibile', 'Achievable total target')} value={p.target} max={row.total} suffix={unitLabel(row.unit, t)} onChange={(v) => update(row.id, 'target', v)} />
            <Input testId={`avoidable-${row.id}`} label={t('Quota di costo realmente eliminabile', 'Cost share actually avoidable')} suffix="%" value={p.avoidablePct} max={100} onChange={(v) => update(row.id, 'avoidablePct', v)} />
            <Input testId={`months-${row.id}`} label={t('Mesi prima dell’attivazione saving', 'Months before savings start')} value={p.months} max={years * 12} onChange={(v) => update(row.id, 'months', v)} />
            <Input testId={`activation-${row.id}`} label={newBusiness ? t('Costo intervento aggiuntivo al progetto base', 'Implementation cost beyond base project') : t('Costo completamento una tantum', 'One-time completion cost')} suffix="€" value={p.activationCost} onChange={(v) => update(row.id, 'activationCost', v)} />
            {row.id === 'endpoint' && <Input label={t('Costo annuo per endpoint dopo intervento', 'Annual cost per endpoint after change')} suffix="€" value={p.endpointAnnualCost} onChange={(v) => update(row.id, 'endpointAnnualCost', v)} />}
            {row.id === 'netscaler' && <Input label={t('Acquisto futuro evitato sul residuo (opzionale)', 'Future purchase avoided on remaining scope (optional)')} suffix="€" value={p.avoidedPurchase} onChange={(v) => update(row.id, 'avoidedPurchase', v)} />}
          </div>
          {row.target !== null && !row.targetValid && <p role="alert" className="mt-3 text-sm text-amber-700">{t('L’obiettivo deve essere compreso tra la quantità già implementata e il totale. Host, utenti e dispositivi devono essere interi.', 'Target must be between current quantity and total. Hosts, users and devices must be whole numbers.')}</p>}
          <label className="mt-4 block text-sm font-medium text-slate-700">{t('Note / evidenze e costi dismessi', 'Notes / evidence and retired costs')}<textarea value={p.evidence ?? ''} onChange={(e) => update(row.id, 'evidence', e.target.value)} className="mt-2 block w-full rounded-xl border border-slate-300 p-3" rows="2" /></label>
          <p className="mt-3 text-xs leading-5 text-slate-500">{t('Saving = quantità aggiuntiva × costo unitario annuo evitabile × quota eliminabile, limitato alla spesa residua. Sul periodo si applicano i mesi effettivi e si sottraggono i costi di intervento.', 'Saving = additional quantity × avoidable annual unit cost × avoidable share, capped at remaining spend. Term savings account for effective months and implementation costs.')}</p>
          {row.id === 'xenserver' && <p className="mt-2 text-xs text-slate-500">{t('Costo host/anno', 'Cost per host/year')}: {state.tech.coresPerHost} × {money(state.cost.costHypervisorPerCoreYear, lang)} = {money(row.unitCost, lang)}. {t('La stima usa core medi per host; la quota eliminabile deve riflettere il contratto effettivo.', 'Estimate uses average cores per host; the avoidable share must reflect the actual contract.')}</p>}
          {row.id === 'endpoint' && <p className="mt-2 text-xs text-slate-500">{t('Conversione eLux ed estensione lifecycle sono conteggiate insieme una sola volta. Costo annuo target = costo di sostituzione / nuovo ciclo di vita.', 'eLux conversion and lifecycle extension are counted together once. Target annual cost = replacement cost / new lifecycle.')}</p>}
          {row.id === 'netscaler' && <p className="mt-2 text-xs text-slate-500">{t('La base annua comprende la manutenzione. Gli acquisti passati non sono saving: inserisci soltanto un refresh futuro effettivamente evitato.', 'Annual baseline includes maintenance. Past purchases are not savings: enter only a future refresh actually avoided.')}</p>}
        </div>
      </details>;
    })}</div>
  </Card>;
}

export function OpportunityTable({ model, lang }) {
  const t = wording(lang);
  return <div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="bg-slate-50 text-xs text-slate-500"><tr>{[t('Leva', 'Lever'), t('Totale', 'Total'), t('Già adottato', 'Already adopted'), t('Obiettivo', 'Target'), t('Da completare', 'Remaining'), t('Saving annuo aggiuntivo', 'Additional annual saving'), t('Saving sul periodo', 'Term saving')].map((label) => <th key={label} className="p-3">{label}</th>)}</tr></thead><tbody>{model.rows.map((row) => <tr key={row.id} className="border-t border-slate-100"><td className="p-3 font-medium">{row.label}<span className="block text-xs font-normal text-slate-500">{unitLabel(row.unit, t)}{!row.complete ? ` · ${t('Da compilare', 'Incomplete')}` : row.excluded ? ` · ${t('Escluso', 'Excluded')}` : ''}</span></td><td className="p-3">{row.total}</td><td className="p-3">{row.currentValid ? row.current : '—'}</td><td className="p-3">{row.targetValid ? row.target : '—'}</td><td className="p-3">{row.targetValid ? row.gap : '—'}</td><td className="p-3">{row.complete ? money(row.annualSaving, lang) : '—'}</td><td className="p-3 font-semibold text-emerald-700">{row.complete ? money(row.periodSaving, lang) : '—'}</td></tr>)}</tbody></table></div>;
}
