const strings = {
  workspace: ['Area di lavoro', 'Workspace', 'Área de trabajo', 'Arbeitsbereich'],
  welcome: ['Costruiamo il tuo scenario.', 'Let’s build your scenario.', 'Construyamos tu escenario.', 'Erstellen wir Ihr Szenario.'],
  intro: ['Pochi passaggi per iniziare. Potrai approfondire ogni ipotesi durante l’analisi.', 'A few steps to get started. Refine every assumption as you work.', 'Unos pasos para empezar. Podrás ajustar cada hipótesis durante el análisis.', 'In wenigen Schritten starten. Annahmen können Sie später verfeinern.'],
  goal: ['Obiettivo', 'Goal', 'Objetivo', 'Ziel'],
  start: ['Punto di partenza', 'Starting point', 'Punto de partida', 'Ausgangspunkt'],
  scope: ['Perimetro', 'Scope', 'Alcance', 'Umfang'],
  setup: ['Configurazione', 'Setup', 'Configuración', 'Konfiguration'],
  newBusiness: ['Nuovo investimento', 'New investment', 'Nueva inversión', 'Neue Investition'],
  renewal: ['Rinnovo contratto', 'Contract renewal', 'Renovación', 'Vertragsverlängerung'],
  businessHint: ['Confronta costi attuali e progetto futuro.', 'Compare current costs with a future project.', 'Compara costes actuales y futuros.', 'Aktuelle und zukünftige Kosten vergleichen.'],
  renewalHint: ['Valuta l’aumento e il valore ancora ottenibile.', 'Assess the increase and remaining value.', 'Evalúa el aumento y el valor disponible.', 'Erhöhung und verbleibendes Potenzial bewerten.'],
  blank: ['Nuovo assessment', 'New assessment', 'Nuevo assessment', 'Neue Bestandsaufnahme'],
  blankHint: ['Parti dai tuoi dati. I valori sconosciuti restano vuoti.', 'Use your own data. Unknown values stay empty.', 'Usa tus datos. Los valores desconocidos quedan vacíos.', 'Eigene Daten verwenden. Unbekannte Werte bleiben leer.'],
  example: ['Esplora un esempio', 'Explore an example', 'Explorar un ejemplo', 'Beispiel ansehen'],
  exampleHint: ['Dati dimostrativi da verificare prima di usare i risultati.', 'Demo data to verify before using the results.', 'Datos de ejemplo que debes verificar.', 'Beispieldaten vor Verwendung der Ergebnisse prüfen.'],
  resume: ['Riprendi la bozza', 'Resume draft', 'Reanudar borrador', 'Entwurf fortsetzen'],
  next: ['Continua', 'Continue', 'Continuar', 'Weiter'],
  back: ['Indietro', 'Back', 'Atrás', 'Zurück'],
  enter: ['Apri area di lavoro', 'Open workspace', 'Abrir área de trabajo', 'Arbeitsbereich öffnen'],
  skip: ['Esplora subito l’esempio', 'Explore the example now', 'Explorar el ejemplo ahora', 'Beispiel jetzt ansehen'],
  data: ['Dati cliente', 'Customer data', 'Datos del cliente', 'Kundendaten'],
  profile: ['Profilo economico', 'Financial profile', 'Perfil económico', 'Wirtschaftliches Profil'],
  adoption: ['Adozione e interventi', 'Adoption and implementation', 'Adopción e intervenciones', 'Einführung und Maßnahmen'],
  results: ['Risultati', 'Results', 'Resultados', 'Ergebnisse'],
  users: ['Utenti e lavoro', 'Users and work', 'Usuarios y trabajo', 'Nutzer und Arbeit'],
  devices: ['Dispositivi', 'Devices', 'Dispositivos', 'Endgeräte'],
  infrastructure: ['Infrastruttura', 'Infrastructure', 'Infraestructura', 'Infrastruktur'],
  security: ['Accesso e sicurezza', 'Access and security', 'Acceso y seguridad', 'Zugriff und Sicherheit'],
  operations: ['Attività IT', 'IT operations', 'Operaciones TI', 'IT-Betrieb'],
  other: ['Altre opportunità', 'Other opportunities', 'Otras oportunidades', 'Weitere Potenziale'],
  all: ['Vista completa', 'Full view', 'Vista completa', 'Gesamtansicht'],
  focused: ['Vista guidata', 'Guided view', 'Vista guiada', 'Geführte Ansicht'],
  missing: ['Da compilare', 'To complete', 'Por completar', 'Auszufüllen'],
  review: ['Da verificare', 'To verify', 'Por verificar', 'Zu prüfen'],
  verified: ['Verificato', 'Verified', 'Verificado', 'Geprüft'],
  confirm: ['Conferma i dati del gruppo', 'Confirm group data', 'Confirmar datos del grupo', 'Gruppendaten bestätigen'],
  shared: ['Dati condivisi: le modifiche aggiornano New Business e Renewal.', 'Shared data: changes update New Business and Renewal.', 'Datos compartidos: los cambios actualizan ambos análisis.', 'Gemeinsame Daten: Änderungen aktualisieren beide Analysen.'],
  unknown: ['Vuoto = non disponibile · 0 = nessun costo o quantità.', 'Empty = unavailable · 0 = no cost or quantity.', 'Vacío = no disponible · 0 = sin coste o cantidad.', 'Leer = unbekannt · 0 = keine Kosten oder Menge.'],
  saving: ['Salvataggio…', 'Saving…', 'Guardando…', 'Speichern…'],
  saved: ['Salvato in questo browser', 'Saved in this browser', 'Guardado en este navegador', 'In diesem Browser gespeichert'],
  saveError: ['Salvataggio non disponibile. Mantieni aperta questa pagina.', 'Saving unavailable. Keep this page open.', 'No se puede guardar. Mantén esta página abierta.', 'Speichern nicht verfügbar. Diese Seite geöffnet lassen.'],
  reset: ['Ripristina New Business', 'Reset New Business', 'Restablecer New Business', 'New Business zurücksetzen'],
  resetConfirm: ['Ripristinare prezzi, durata e adozione New Business? I dati cliente e il rinnovo restano invariati.', 'Reset New Business prices, duration and adoption? Customer data and renewal stay unchanged.', '¿Restablecer precios, duración y adopción New Business? Los datos del cliente y renovación se conservan.', 'Preise, Laufzeit und Einführung für New Business zurücksetzen? Kundendaten und Verlängerung bleiben erhalten.'],
  method: ['Metodo e ipotesi', 'Method and assumptions', 'Método e hipótesis', 'Methode und Annahmen'],
  help: ['Aiuto', 'Help', 'Ayuda', 'Hilfe'],
  provisional: ['Stima provvisoria', 'Provisional estimate', 'Estimación provisional', 'Vorläufige Schätzung'],
  reviewHint: ['Verifica i dati iniziali e completa le ipotesi prima di utilizzare i risultati.', 'Verify initial data and complete assumptions before using results.', 'Verifica los datos iniciales y completa las hipótesis.', 'Ausgangsdaten prüfen und Annahmen vervollständigen.'],
  capacity: ['Le giornate IT liberate non equivalgono automaticamente a minori esborsi.', 'Released IT capacity does not automatically mean cash savings.', 'La capacidad TI liberada no equivale automáticamente a ahorro monetario.', 'Freie IT-Kapazität bedeutet nicht automatisch geringere Ausgaben.'],
  checklist: ['Gruppi verificati', 'Verified groups', 'Grupos verificados', 'Geprüfte Gruppen'],
  scopeHint: ['Scegli da dove iniziare. Tutte le aree rimangono disponibili e nessuna voce viene esclusa dai calcoli.', 'Choose where to start. All areas remain available; no item is excluded from calculations.', 'Elige dónde empezar. Todas las áreas siguen disponibles; no se excluye ningún cálculo.', 'Startbereich wählen. Alle Bereiche bleiben verfügbar; keine Position wird aus Berechnungen ausgeschlossen.'],
  exampleBadge: ['Esempio · dati da verificare', 'Example · verify data', 'Ejemplo · verificar datos', 'Beispiel · Daten prüfen'],
  blankBadge: ['Dati cliente · verifica in corso', 'Customer data · review in progress', 'Datos del cliente · revisión pendiente', 'Kundendaten · Prüfung läuft'],
  invalid: ['Inserisci un valore valido', 'Enter a valid value', 'Introduce un valor válido', 'Gültigen Wert eingeben'],
  newAnalysis: ['Guida iniziale', 'Getting started', 'Guía inicial', 'Einstieg'],
  retained: ['La bozza attuale sarà sostituita solo aprendo la nuova area di lavoro.', 'Your draft is replaced only when you open the new workspace.', 'El borrador se sustituye solo al abrir la nueva área de trabajo.', 'Der Entwurf wird erst beim Öffnen des neuen Arbeitsbereichs ersetzt.'],
};
export const workspaceText = (lang = 'en') => (key) => strings[key]?.[{ it: 0, en: 1, es: 2, de: 3 }[lang] ?? 1] ?? key;
